# Funding & Support

## 💼 Commercial License

For commercial projects, themes, and applications, please purchase a commercial license:

**[Purchase Commercial License →](https://www.viov.nl/)**

Benefits of Commercial License:
- Keep your source code proprietary
- Priority email support
- Custom feature development options
- License for unlimited projects
- Lifetime updates

## 🎯 Consulting & Custom Development

Need help with integration, custom features, or professional services?

**Contact:** hi@viov.nl  
**Website:** [https://www.viov.nl/](https://www.viov.nl/)

## 💝 Sponsorship

If you find this project useful, consider sponsoring its development:

- GitHub Sponsors: [Sponsor VIOVNL](https://github.com/sponsors/VIOVNL)
- Custom: Contact us at hi@viov.nl

Your sponsorship helps us:
- Maintain and improve the library
- Add new features and components
- Provide better documentation
- Offer community support

## 📞 Get in Touch

- **Email:** hi@viov.nl
- **Website:** [https://www.viov.nl/](https://www.viov.nl/)
- **GitHub Issues:** [Report a bug or request a feature](https://github.com/VIOVNL/Flowy.Blazor/issues)

Thank you for your support! 🙏
